### ISSUE TITLE
Avoid installation of luci-openwisp

### ISSUE THREAD

**Issue by marino-mrc** [openwisp/ansible-openwisp2-imagegenerator#13]
Hello, is there a way to avoid the installation of luci-openwisp? Can you provide a complete example of the playbook.yml file to do this? I need to install the complete luci web interface because I'd like to accomplish some task through the web interface
Thank you

**Comment by nemesifier** [comment]
Try this and let me know if it works so I can add an example in the README:

```yaml
# playbook.yml
- hosts: your_host_here
  roles:
    - openwisp.openwisp2-imagegenerator
  vars:
    openwisp2fw_source_default_packages:
      - openwisp-config-{{ openwisp2fw_ssl_lib }}
      - openvpn-{{ openwisp2fw_ssl_lib }}
```
