### ISSUE TITLE
[question] firmware-upgrader

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2-imagegenerator#27]
Your esample:
```yml
  vars:
    openwisp2fw_controller_url: "https://openwisp.myproject.com"
    openwisp2fw_organizations:
      - name: prod
        flavours:
          - default
        openwisp:
          url: "{{ openwisp2fw_controller_url }}"
          shared_secret: "xxxxx"
        root_password: "xxxxx"
        categories:
          default: <CATEGORY-UUID>
    openwisp2fw_uploader:
        enabled: true
        url: "{{ openwisp2fw_controller_url }}"
        token: "<REST-API-USER-TOKEN>"
        image_types:
            - ath79-generic-ubnt_airrouter-squashfs-sysupgrade.bin
            - ar71xx-generic-ubnt-bullet-m-xw-squashfs-sysupgrade.bin
            - ar71xx-generic-ubnt-bullet-m-squashfs-sysupgrade.bin
```

if by hypothesis i have any flavours and categories.
For flavours the build is in the folder "name_organizations/flavours_1, 2, 3
how it works with categories A, B and C?
an image has all categories?
Thanks

**Comment by nemesifier** [comment]
You need to create a category for each flavour:

```
openwisp2fw_organizations:
      - name: <ORGANIZATION_NAME>
        flavours:
          - <FLAVOUR_A>
          - <FLAVOUR_B>
        openwisp:
          url: "{{ openwisp2fw_controller_url }}"
          shared_secret: "xxxxx"
        root_password: "xxxxx"
        categories:
          <FLAVOUR_A>: <CATEGORY-FLAVOUR-A-UUID>
          <FLAVOUR_B>: <CATEGORY-FLAVOUR-B-UUID>
```

Is this clear?

Bytheway, I verified the possibility of having a different version identifier in each flavour but it's not doable, the version identifier is generated at compile time.
